### ISSUE TITLE
Рекомендации по улучшению

### ISSUE THREAD

**Issue by heX16** [farag2/ADB-Debloating#1]
Глянул код - удаляется очень много софта от google а не от xiaomi, причем зачастую удаляется реально нужный и используемый софт. Если честно вообще не уверен в безопасности таких манипуляций...
В описание надо добавить предупреждение о небезопасности действий и что много полезного софта пропадет.

При этом очень много не нужного/вредного софта от Xiaomi не удаляется.
Рекомендую глянуть вот этот [репозиторий](https://gitlab.com/W1nst0n/universal-android-debloater), там список гораздо больше: https://github.com/farag2/ADB-Debloating/blob/master/MIUI.cmd

**Comment by farag2** [comment]
> Если честно вообще не уверен в безопасности таких манипуляций...
Я уверен.

> Рекомендую глянуть вот этот репозиторий
Ничего нового не обнаружил для себя: все или уже добавлено в скрипт, или на моем Mi 10T такого и нет.
