### ISSUE TITLE
Не надо удалять живые обои

### ISSUE THREAD

**Issue by feivur** [farag2/ADB-Debloating#2]
После запуска скрипта обнаружил, что пропала возможность установки живых обоев. Посмотрел код, так и есть, удаляется 
com.android.wallpaper.livepicker

**Comment by farag2** [comment]
> После запуска скрипта обнаружил, что пропала возможность установки живых обоев. Посмотрел код, так и есть, удаляется
> com.android.wallpaper.livepicker

А зачем удалил?
