### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by IB-IN** [farag2/ADB-Debloating#7]
Why doing that much in a script writing same code again n again. heres my sample script.

`@echo off & title Universal Android Debloater & color 17

cd /d %~dp0

adb devices -l

pause

Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Write-Host 'Removing Packages' -ForegroundColor Green"
for %%z in (

Each & every package name in a new line

) do ( 
adb shell pm clear %%z
adb shell pm uninstall --user 0 %%z
)

Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Write-Host 'Clear Logs' -ForegroundColor Green"
adb logcat -c

Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Write-Host 'Reset Battery State' -ForegroundColor Green"
adb shell dumpsys battery reset

Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Write-Host 'Full Battery State' -ForegroundColor Green"
adb shell dumpsys battery`

**Comment by farag2** [comment]
actually, you're right. All because I forgot how to code in batch. I prefer normal languages. Could you please re-write the script to use ForEach-Object like in PowerShell?

**Comment by IB-IN** [comment]
What about restore settings after a hard reset :

adb shell settings put global "saettings name" "setting value"
adb shell settings put system "saettings name" "setting value"
adb shell settings put secure "saettings name" "setting value"

( This Way User Dont have to sett his or her settings again n again after a reset )

Regards 👍🏻

**Comment by farag2** [comment]
I'm not an expert in adb at all. just know these commands. So I didn't get the point of your suggestion. 😸

**Comment by farag2** [comment]
You're like my manager in Poland: every time he introduces me to an IT managers which have high position in the corporation, he always adds that "This is Dmitry, a PowerShell expert", and then my "No, no, do not think this way, I'm just an enthusiast living his job"! 😹 

Anyway, I'm too tired of thinking today. I will get back when I release my SophiApp for all. May be on the next week. We're just waiting for the German translation from the native...
https://github.com/Sophia-Community/SophiApp
